// src/common/exceptions/error-codes.ts

/**
 * Centralized error code registry.
 *
 * Every business error in the system has a unique, stable code.
 * These codes are used in API responses and must NEVER change
 * once published (clients may depend on them).
 *
 * Naming convention: MODULE_SPECIFIC_ERROR
 */
export const ErrorCodes = {
  // ── General ──
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  OPERATION_NOT_PERMITTED: 'OPERATION_NOT_PERMITTED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ── Tenant ──
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_TERMINATED: 'TENANT_TERMINATED',
  TENANT_PLAN_LIMIT_REACHED: 'TENANT_PLAN_LIMIT_REACHED',

  // ── Auth ──
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID: 'AUTH_MFA_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',

  // ── Employee ──
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_ALREADY_EXISTS: 'EMPLOYEE_ALREADY_EXISTS',
  EMPLOYEE_NOT_ACTIVE: 'EMPLOYEE_NOT_ACTIVE',
  EMPLOYEE_ALREADY_TERMINATED: 'EMPLOYEE_ALREADY_TERMINATED',

  // ── Attendance ──
  ATTENDANCE_ALREADY_CHECKED_IN: 'ATTENDANCE_ALREADY_CHECKED_IN',
  ATTENDANCE_NOT_CHECKED_IN: 'ATTENDANCE_NOT_CHECKED_IN',
  ATTENDANCE_OUTSIDE_GEOFENCE: 'ATTENDANCE_OUTSIDE_GEOFENCE',
  ATTENDANCE_INVALID_DEVICE: 'ATTENDANCE_INVALID_DEVICE',
  ATTENDANCE_RECORD_LOCKED: 'ATTENDANCE_RECORD_LOCKED',

  // ── Leave ──
  LEAVE_INSUFFICIENT_BALANCE: 'LEAVE_INSUFFICIENT_BALANCE',
  LEAVE_OVERLAP_EXISTS: 'LEAVE_OVERLAP_EXISTS',
  LEAVE_REQUEST_NOT_FOUND: 'LEAVE_REQUEST_NOT_FOUND',
  LEAVE_ALREADY_APPROVED: 'LEAVE_ALREADY_APPROVED',
  LEAVE_ALREADY_CANCELLED: 'LEAVE_ALREADY_CANCELLED',
  LEAVE_CANNOT_CANCEL_TAKEN: 'LEAVE_CANNOT_CANCEL_TAKEN',
  LEAVE_MIN_NOTICE_NOT_MET: 'LEAVE_MIN_NOTICE_NOT_MET',

  // ── Payroll ──
  PAYROLL_RUN_NOT_FOUND: 'PAYROLL_RUN_NOT_FOUND',
  PAYROLL_RUN_ALREADY_EXISTS: 'PAYROLL_RUN_ALREADY_EXISTS',
  PAYROLL_RUN_ALREADY_FINALIZED: 'PAYROLL_RUN_ALREADY_FINALIZED',
  PAYROLL_RUN_INVALID_STATUS: 'PAYROLL_RUN_INVALID_STATUS',
  PAYROLL_UNRESOLVED_ANOMALIES: 'PAYROLL_UNRESOLVED_ANOMALIES',
  PAYROLL_CALCULATION_FAILED: 'PAYROLL_CALCULATION_FAILED',
  PAYROLL_SNAPSHOT_IMMUTABLE: 'PAYROLL_SNAPSHOT_IMMUTABLE',

  // ── Config ──
  CONFIG_POLICY_NOT_FOUND: 'CONFIG_POLICY_NOT_FOUND',
  CONFIG_INVALID_POLICY_DATA: 'CONFIG_INVALID_POLICY_DATA',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
