// src/database/schema/employee-devices.ts

import {
  pgTable,
  uuid,
  varchar,
  boolean,
  timestamp,
  index,
  uniqueIndex,
} from 'drizzle-orm/pg-core';
import { primaryId, tenantId } from './base.columns';

/**
 * Employee devices — registered mobile devices for GPS check-in.
 *
 * Design decisions:
 *
 * 1. Tenant-scoped:
 *    A device is registered per employee per tenant. The same physical
 *    phone used by an employee at two tenants creates two device records.
 *    This keeps tenant data isolation clean.
 *
 * 2. No FK to employees in Drizzle schema:
 *    Same circular-dependency avoidance pattern as employees → users.
 *    Enforced at the application layer.
 *
 * 3. Soft deactivation:
 *    Devices are deactivated, never hard-deleted. Historical check-in
 *    records reference the device_id; hard-deleting would break audit trails.
 *
 * 4. FCM token is mutable:
 *    Firebase Cloud Messaging tokens rotate periodically. The app refreshes
 *    the token without re-registering the device via the dedicated
 *    PATCH /devices/:id/fcm-token endpoint.
 *
 * 5. deviceId is a client-provided fingerprint string:
 *    Not a UUID — it is the hardware/OS fingerprint generated by the mobile app.
 *    Unique per (tenant_id, employee_id, device_id) to prevent re-registration
 *    of the same physical device while still allowing the same device to be
 *    registered across different employees or tenants.
 *
 * 6. This table HAS RLS (tenant_id scoped).
 */
export const employeeDevices = pgTable(
  'employee_devices',
  {
    ...primaryId,
    ...tenantId,

    // References employees.id — enforced at application layer.
    employeeId: uuid('employee_id').notNull(),

    // Client-generated device fingerprint (OS + hardware identifier).
    // Max 255 chars to accommodate various platform fingerprint formats.
    deviceId: varchar('device_id', { length: 255 }).notNull(),

    // Human-readable label set by the employee (e.g., "Alice's iPhone 15")
    deviceName: varchar('device_name', { length: 255 }),

    // Operating system for display and analytics purposes
    deviceOs: varchar('device_os', { length: 50 }),
    // 'ios' | 'android' | 'web'

    // Firebase Cloud Messaging token for push notifications.
    // Nullable — employee may not grant notification permission.
    fcmToken: varchar('fcm_token', { length: 500 }),

    // Soft deactivation — never hard-delete (preserves attendance audit trail)
    isActive: boolean('is_active').notNull().default(true),

    // When the device was first registered
    registeredAt: timestamp('registered_at', { withTimezone: true })
      .notNull()
      .defaultNow(),

    // When the device was last used to check in
    lastUsedAt: timestamp('last_used_at', { withTimezone: true }),
  },
  (table) => ({
    // Primary uniqueness: one physical device per employee per tenant
    // Prevents duplicate registrations of the same device
    tenantEmployeeDeviceUnique: uniqueIndex(
      'idx_employee_devices_tenant_employee_device_unique',
    ).on(table.tenantId, table.employeeId, table.deviceId),

    // Lookup: get all devices for an employee
    employeeIdx: index('idx_employee_devices_employee').on(
      table.tenantId,
      table.employeeId,
    ),

    // Attendance check-in validation: look up device during check-in
    deviceLookupIdx: index('idx_employee_devices_device_lookup').on(
      table.tenantId,
      table.deviceId,
    ),
  }),
);

export type EmployeeDevice = typeof employeeDevices.$inferSelect;
export type NewEmployeeDevice = typeof employeeDevices.$inferInsert;
